[package]
name = "dialog"
version = "0.1.0"
edition = "2024"
build = "./build.rs"

[workspace]
members = [
 "utils",
 "generate",
]

[dependencies]
utils = { path = "./utils/" }
generate = { path = "./generate/" }
clap = { version = "4.5.42", features = ["derive"] }
rand = "0.9.2"
